# -*- mode: python ; coding: utf-8 -*-
import os
from PyInstaller.utils.hooks import collect_all

# Include baked config when present (generated by GitHub Actions for customer builds)
_baked_datas = []
if os.path.exists("_desktop_build_config.py"):
    _baked_datas = [("_desktop_build_config.py", ".")]

# Collect all Textual submodules + CSS/theme data files
_textual_datas, _textual_binaries, _textual_hiddenimports = collect_all("textual")

a = Analysis(
    ["burnBot.py"],
    pathex=[],
    binaries=_textual_binaries,
    datas=_baked_datas + _textual_datas,
    hiddenimports=[
        *_textual_hiddenimports,
        "selenium.webdriver.chrome.webdriver",
        "selenium.webdriver.chrome.service",
        "selenium.webdriver.chrome.options",
        "selenium.webdriver.common.service",
        "selenium.webdriver.common.utils",
        "selenium.webdriver.remote.remote_connection",
        "selenium.webdriver.support.ui",
        "selenium.webdriver.support.expected_conditions",
        "selenium.webdriver.support.wait",
        "_desktop_build_config",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="SlowBurnBot",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
